export const dataSets = [
  {
    title: "Dataset Long Title Irena Renewable Energy Statistics Lorem Ipsum do max 80 chars",
    img: "tempDataSetImage1.jpg",
    description:
      "Dataset Description Detailed statistics on renewable energy capacity, power generation and renewable energy balances. Lorem ipsum dolor sit amet, consectet adipiscing elit sed max 190 chars.",
    lastUpdate: "01-06-2022",
    frequency: "3 months",
    geography: "North America",
    tags: [
      "biofuel",
      "biogas",
      "biogas",
      "emissions",
      "hydropower",
      "photovoltaic",
      "renewable energy",
      "technology",
      "solar power",
      "wind power",
    ],
  },
  {
    title: "European Data Portal",
    img: "tempDataSetImage2.jpg",
    description:
      "Dataset Description Detailed statistics on renewable energy capacity, power generation and renewable energy balances. Lorem ipsum dolor sit amet, consectet adipiscing elit sed max 190 chars.",
    lastUpdate: "01-06-2022",
    frequency: "3 months",
    geography: "North America",
    tags: ["biofuel", "biogas", "biogas", "emissions", "hydropower", "photovoltaic"],
  },
  {
    title: "Figshare – River Plastic Emissions to the World’s Oceans ",
    img: "tempDataSetImage3.jpg",
    description:
      "Dataset Description Detailed statistics on renewable energy capacity, power generation and renewable energy balances. Lorem ipsum dolor sit amet, consectet adipiscing elit sed max 190 chars.",
    lastUpdate: "01-06-2022",
    frequency: "3 months",
    geography: "North America",
    tags: ["biofuel", "biogas"],
  },
  {
    title: "Dataset Long Title Irena Renewable Energy Statistics Lorem Ipsum do max 80 chars",
    img: "tempDataSetImage1.jpg",
    description:
      "Dataset Description Detailed statistics on renewable energy capacity, power generation and renewable energy balances. Lorem ipsum dolor sit amet, consectet adipiscing elit sed max 190 chars.",
    lastUpdate: "01-06-2022",
    frequency: "3 months",
    geography: "North America",
    tags: ["biofuel", "biogas", "biogas"],
  },
  {
    title: "Dataset Long Title Irena Renewable Energy Statistics Lorem Ipsum do max 80 chars",
    img: "tempDataSetImage2.jpg",
    description:
      "Dataset Description Detailed statistics on renewable energy capacity, power generation and renewable energy balances. Lorem ipsum dolor sit amet, consectet adipiscing elit sed max 190 chars.",
    lastUpdate: "01-06-2022",
    frequency: "3 months",
    geography: "North America",
    tags: [
      "biofuel",
      "biogas",
      "biogas",
      "emissions",
      "hydropower",
      "photovoltaic",
      "renewable energy",
      "technology",
      "solar power",
      "wind power",
    ],
  },
  {
    title: "Dataset Long Title Irena Renewable Energy Statistics Lorem Ipsum do max 80 chars",
    img: "tempDataSetImage3.jpg",
    description:
      "Dataset Description Detailed statistics on renewable energy capacity, power generation and renewable energy balances. Lorem ipsum dolor sit amet, consectet adipiscing elit sed max 190 chars.",
    lastUpdate: "01-06-2022",
    frequency: "3 months",
    geography: "North America",
    tags: [
      "biofuel",
      "biogas",
      "biogas",
      "emissions",
      "hydropower",
      "photovoltaic",
      "renewable energy",
      "technology",
      "solar power",
      "wind power",
    ],
  },
];
